version: '3.8'

services:
  neo4j:
    image: neo4j:5.20.0
    container_name: neo4j_health_graph
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt protocol for our Python driver
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j_data:/data
    restart: unless-stopped
